services:
  - type: web
    name: elmnsa-backend
    env: docker
    rootDir: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
